# Generated by Django 3.2.5 on 2021-07-21 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210322_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+99999'. Up to 14 digits allowed.", regex='^\\+?|d{9,14}$')]),
        ),
    ]
